spring:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:h2:mem:reviews
    driverClassName: org.h2.Driver
    username: sa
server:
  port: 9001